include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    camel_case_types: ignore
    deprecated_member_use: ignore
  exclude:
    - build/**

linter:
  rules:
    camel_case_types: false
    prefer_const_constructors: false
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_const: true
    always_declare_return_types: true
